//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RpgSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet
    {
        public int Id { get; set; }
        public int IdCampaing { get; set; }
        public int IdPlayer { get; set; }
    
        public virtual Campaing Campaing { get; set; }
        public virtual Players Players { get; set; }
    }
}
